language: android
android:
  components:
    - build-tools-22.0.1
    - android-23
    - extra-android-m2repository
    - extra-android-support
before_install:
- chmod +x gradlew
#script:
 # - ./ReadWorld/gradlew assembleRelease
